site_name: Do zero a implantaÃ§Ã£o
theme:
  name: material
  language: pt
  palette: 
    - scheme: default
      primary: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate 
      primary: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    logo: material/rocket
  favicon: imgs/favicon.ico
  features:
    - content.tabs.link
markdown_extensions:
  - pymdownx.emoji
  - pymdownx.tasklist:
     custom_checkbox: true
  - pymdownx.superfences
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html
repo_name: cassiobotaro/do_zero_a_implantacao
repo_url: https://github.com/cassiobotaro/do_zero_a_implantacao

nav:
  - â–¶ï¸ IntroduÃ§Ã£o: index.md
  - ğŸ’­ Planejando o que serÃ¡ desenvolvido: planejando.md
  - ğŸ”¨ Escolhendo as melhores ferramentas: ferramentas.md
  - ğŸ“– Iniciando o projeto: projeto.md
  - ğŸŒ Um pouco sobre a web: web.md
  - ğŸ Primeiros passos com python: python.md
  - ğŸ Desenvolvimento guiado por testes: testes.md
  - âš¡ï¸ Hello Fastapi: hello_fastapi.md
  - âœ”ï¸ IntegraÃ§Ã£o contÃ­nua: integracao.md
  - ğŸš€ Mandando um foguete pro espaÃ§o: deploy.md
  - ğŸ“ Criando uma tarefa: criar.md
  - ğŸ† O desafio: desafio.md
  - ğŸ“‘ ReferÃªncias e Dicas: referencias.md

